@extends('layouts.app')
@section('title','Overview')
@section('content')
<div class="page-heading"><div><span class="eyebrow">YOUR WORKSPACE AT A GLANCE</span><h1>A good day starts with a clear view.</h1><p>Here’s how your {{ auth()->user()->isOwner()?'team is':'calls are' }} doing. Let’s keep the conversations moving.</p></div>@if(auth()->user()->isOwner())<a class="button primary" href="{{ route('leads.create') }}"><x-icon name="plus" size="18"/>Add lead</a>@endif</div>
<form class="date-toolbar" method="get"><div class="section-label"><span class="online-dot"></span> Activity overview <span class="muted">· IST</span></div><div class="date-inputs"><label class="sr-only" for="from">From date</label><input id="from" aria-label="From date" name="from" type="date" value="{{ $from }}"><span>to</span><label class="sr-only" for="to">To date</label><input id="to" aria-label="To date" name="to" type="date" value="{{ $to }}"><button class="button subtle small">Apply</button><a class="text-link" href="{{ route('dashboard') }}">Today</a></div></form>
@unless(\App\Models\Call::demoEnabled())
<div class="info-box" style="margin-bottom:18px">Only provider-verified calls count toward activity and talk time. {{ $unverified }} request(s) in this period are unverified and excluded. Employee notes and lead stages are not proof of a call.</div>
@endunless
<div class="stats-grid">
@foreach([[\App\Models\Call::demoEnabled()?'Demo call attempts':'Verified call attempts',$stats['attempts'],'phone',\App\Models\Call::demoEnabled()?'Simulated activity only':'Confirmed against provider records','blue'],['Customers connected',$stats['connected'],'users',\App\Models\Call::demoEnabled()?'Simulated connections':'Verified customer connections','green'],['Conversation time',\App\Support\India::duration($stats['talk']),'clock','Known customer talk time','violet'],['Leads converted',$stats['conversions'],'chart','Current conversions in this period','amber']] as [$label,$value,$icon,$hint,$tone])
<div class="stat-card"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon {{ $tone }}"><x-icon :name="$icon" size="19"/></span></div><strong class="stat-value">{{ $value }}</strong><small>{{ $hint }}</small></div>
@endforeach
</div>
<div class="attention-strip"><div class="attention-title"><span class="attention-icon"><x-icon name="calendar"/></span><div><strong>A little attention goes a long way</strong><small>Pending work, as of right now</small></div></div><a href="{{ route('follow-ups.index',['filter'=>'overdue']) }}"><strong class="red-text">{{ $stats['overdue'] }}</strong> overdue follow-ups <x-icon name="arrow" size="16"/></a><a href="{{ route('follow-ups.index',['filter'=>'today']) }}"><strong>{{ $stats['due'] }}</strong> due today <x-icon name="arrow" size="16"/></a><a href="{{ route('leads.index',['attention'=>'never']) }}"><strong>{{ $stats['never'] }}</strong> leads without verified calls <x-icon name="arrow" size="16"/></a></div>
<div class="dashboard-columns"><section class="panel"><div class="panel-heading"><div><h2>Team activity</h2><p>Call attempts and connections in the selected period</p></div><span class="label-chip">{{ $performance->count() }} {{ \Illuminate\Support\Str::plural('employee',$performance->count()) }}</span></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Attempts</th><th>Connected</th><th>Talk time</th><th>Connection rate</th></tr></thead><tbody>@forelse($performance as $row)<tr><td><div class="person"><span class="avatar small-avatar">{{ mb_substr($row['employee']->name,0,1) }}</span><div><strong>{{ $row['employee']->name }}</strong><small>{{ $row['employee']->active?'Employee':'Inactive' }}</small></div></div></td><td>{{ $row['attempts'] }}</td><td>{{ $row['connected'] }}</td><td class="nowrap">{{ \App\Support\India::duration($row['talk']) }}</td><td><div class="rate"><div class="rate-track"><span style="width:{{ $row['attempts']?round($row['connected']/$row['attempts']*100):0 }}%"></span></div><span>{{ $row['attempts']?round($row['connected']/$row['attempts']*100):0 }}%</span></div></td></tr>@empty<tr><td colspan="5" class="empty">Add employees to start tracking team activity.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Lead pipeline</h2><p>Employee-reported stages · {{ $stats['total_leads'] }} total leads</p></div><x-icon name="chart"/></div><div class="pipeline">@foreach(\App\Models\Lead::STAGES as $stage)<a class="pipeline-row" href="{{ route('leads.index',['stage'=>$stage]) }}"><div><span>{{ $stage }}</span><strong>{{ $stageCounts[$stage]??0 }}</strong></div><div class="pipeline-track"><span class="stage-{{ strtolower($stage) }}" style="width:{{ $stats['total_leads']?max(0,($stageCounts[$stage]??0)/$stats['total_leads']*100):0 }}%"></span></div></a>@endforeach</div><div class="panel-foot"><a class="text-link" href="{{ route('leads.index') }}">Explore all leads <x-icon name="arrow" size="16"/></a></div></section></div>
<div class="dashboard-columns lower"><section class="panel"><div class="panel-heading"><div><h2>Recent conversations</h2><p>The latest call activity in this period</p></div><a class="text-link" href="{{ route('calls.index',['from'=>$from,'to'=>$to]) }}">View all <x-icon name="arrow" size="15"/></a></div>@include('calls.table',['calls'=>$recent,'compact'=>true])</section>
<section class="panel"><div class="panel-heading"><div><h2>Up next</h2><p>Your next follow-ups, overdue first</p></div><a class="text-link" href="{{ route('follow-ups.index') }}">View all</a></div><div class="up-next">@forelse($due as $item)<a href="{{ route('leads.show',$item->lead) }}" class="up-next-row"><span class="follow-icon {{ $item->due_at->isPast()?'overdue':'' }}"><x-icon name="calendar" size="18"/></span><div><strong>{{ $item->lead->name }}</strong><small>{{ \Illuminate\Support\Str::limit($item->note,48) }}</small><span class="{{ $item->due_at->isPast()?'red-text':'muted' }} tiny">{{ \App\Support\India::display($item->due_at,'d M, h:i A') }} · {{ $item->employee->name }}</span></div><x-icon name="arrow" size="16"/></a>@empty<div class="empty">You’re all caught up.<br><small>Scheduled follow-ups will appear here.</small></div>@endforelse</div></section></div>
@endsection
