@extends('layouts.app')
@section('title','Settings')
@section('content')
<div class="page-heading"><div><span class="eyebrow">WORKSPACE HEALTH</span><h1>Settings & operations</h1><p>Calling configuration, background processing, and account activity.</p></div></div>
<div class="stats-grid"><div class="stat-card"><span>Calling mode</span><strong class="stat-value mode-value">{{ config('telephony.driver')==='demo'?'Demo':'Exotel' }}</strong><small>{{ $ready?'Live configuration present':'Live calling not enabled' }}</small></div><div class="stat-card"><span>Queued jobs</span><strong class="stat-value">{{ $pendingJobs }}</strong><small>Waiting for background processing</small></div><div class="stat-card"><span>Failed jobs</span><strong class="stat-value">{{ $failedJobs }}</strong><small>Review with php artisan queue:failed</small></div><div class="stat-card"><span>Event verification issues</span><strong class="stat-value">{{ $eventErrors }}</strong><small>Pending retries or reconciliation</small></div></div>
<div class="panel"><div class="panel-heading"><h2>Calling setup</h2><span class="label-chip">India only · Recording off</span></div><div class="panel-body"><p>Provider credentials are managed in the server’s <code>.env</code> file. They are never shown or edited in the browser.</p><p class="muted">To enable Exotel: configure the account, API key/token, approved caller ID, public HTTPS callback URL, and set TELEPHONY_DRIVER=exotel and TELEPHONY_LIVE_ENABLED=true. Follow the deployment guide in docs/DEPLOYMENT.md and run a controlled test before onboarding the team.</p><p class="help-note">Background worker and scheduler must be running. A configured account is not proof that your calling route has been approved.</p></div></div>
<section class="panel section-gap"><div class="panel-heading"><div><h2>Calls needing attention</h2><p>Unfinished or uncertain calls older than five minutes</p></div></div><div class="panel-body stack">@forelse($unresolved as $call)<div class="follow-card"><h3>Call #{{ $call->id }} · {{ $call->lead->name }}</h3><p>{{ $call->employee->name }} · {{ \App\Support\India::display($call->initiated_at) }} IST · {{ $call->status }}</p>@if($call->provider==='exotel')<form class="inline-form" method="post" action="{{ route('calls.reconcile',$call) }}">@csrf @unless($call->provider_sid)<input name="provider_sid" aria-label="Provider call SID" placeholder="Call SID from Exotel logs" required>@endunless<button class="button small">Verify with Exotel</button></form>@endif<details><summary>Release a stuck call after checking provider logs</summary><form class="stack" action="{{ route('calls.resolve',$call) }}" method="post">@csrf<p class="help-note">This only permits a new attempt. It does not change this call into a successful or failed call.</p><label>Reason and provider verification notes<textarea name="reason" minlength="15" maxlength="1000" required></textarea></label><label class="checkbox"><input type="checkbox" name="confirmed" value="1" required>I verified that this call is no longer active with the provider.</label><button class="button small">Release call lock</button></form></details></div>@empty<p class="muted">No calls need attention right now.</p>@endforelse</div></section>
<section class="panel section-gap"><div class="panel-heading"><h2>Administrative activity</h2></div><div class="table-wrap"><table><thead><tr><th>When · IST</th><th>Who</th><th>Action</th><th>Details</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ \App\Support\India::display($audit->created_at) }}</td><td>{{ $audit->user?->name??'System' }}</td><td>{{ $audit->action }}</td><td>{{ $audit->description }}</td></tr>@empty<tr><td colspan="4" class="empty">Administrative changes will appear here.</td></tr>@endforelse</tbody></table></div></section>
@endsection
