@extends('layouts.app')
@section('title','Lead detail')
@section('content')
<div class="page-heading"><div><a class="text-link" href="{{ route('leads.index') }}">← Back to leads</a><h1>{{ $lead->name }}</h1><p>{{ $lead->phone }} <span class="separator">·</span> {{ $lead->source }} <span class="separator">·</span> Added {{ \App\Support\India::display($lead->created_at,'d M Y') }}</p></div><div class="actions"><a class="button" href="{{ route('leads.edit',$lead) }}">{{ auth()->user()->isOwner()?'Edit lead':'Update stage' }}</a>@if(!auth()->user()->isOwner() && $lead->assigned_to===auth()->id())<form action="{{ route('calls.store',$lead) }}" method="post">@csrf<input type="hidden" name="request_key" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="button primary"><x-icon name="phone" size="18"/>{{ \App\Models\Call::demoEnabled()?'Start demo call':'Call lead' }}</button></form>@endif</div></div>
<div class="lead-summary"><div><span class="muted">Reported lead stage</span><x-badge :value="$lead->stage"/></div><div><span class="muted">Assigned employee</span><strong>{{ $lead->assignee?->name??'Unassigned' }}</strong></div><div><span class="muted">Call requests</span><strong>{{ $calls->total() }}</strong></div><div><span class="muted">Pending follow-ups</span><strong>{{ $followUps->whereNull('completed_at')->count() }}</strong></div></div>
@foreach($calls as $call)
@if(\App\Models\Call::demoEnabled() && $call->isActive() && $call->provider==='demo' && $call->employee_id===auth()->id())<section class="panel demo-simulator"><div class="panel-heading"><div><h2>Demo call in progress</h2><p>No phones are ringing. Choose a result to try automatic call history.</p></div><span class="demo-tag">SIMULATION</span></div><form class="filter-bar" action="{{ route('calls.demo',$call) }}" method="post">@csrf<label>Customer outcome<select name="outcome"><option value="connected">Connected</option><option value="no-answer">No answer</option><option value="busy">Busy</option><option value="failed">Failed</option></select></label><label>Simulated talk time (seconds)<input name="duration" type="number" value="120" min="0" max="3600" required></label><button class="button primary">Finish demo call</button></form></section>@elseif($call->isActive())<div class="alert warning">Call #{{ $call->id }}: {{ $call->error_message??'Awaiting provider updates. Refresh this page after the call finishes.' }}</div>@endif
@endforeach
<div class="detail-columns"><div class="stack"><section class="panel"><div class="panel-heading"><h2>Employee notes</h2><x-icon name="users"/></div><form class="panel-body stack" action="{{ route('leads.notes',$lead) }}" method="post">@csrf<label class="sr-only" for="note">Discussion notes</label><textarea id="note" name="note" rows="3" maxlength="5000" placeholder="What did you discuss? Capture the details for the next conversation." required>{{ old('note') }}</textarea><div class="align-end"><button class="button primary small">Save note</button></div></form></section>
<section class="panel"><div class="panel-heading"><div><h2>System call history</h2><p>One record per attempt · All times in IST</p></div><a class="text-link" href="{{ route('leads.show',$lead) }}">Refresh</a></div><div class="call-details-list">@forelse($calls as $call)<div class="call-detail"><div class="call-detail-head"><div><strong>{{ $call->employee->name }}</strong><small>{{ \App\Support\India::display($call->initiated_at) }} IST @if($call->provider==='demo')· Demo @endif</small></div><x-badge :value="$call->customer_status"/></div><div class="call-facts"><span>Talk time <strong>{{ \App\Support\India::duration($call->duration_seconds) }}</strong></span><span>Ended <strong>{{ \App\Support\India::display($call->ended_at,'h:i A') }}</strong></span><span>Call state <strong>{{ $call->status }}</strong></span><span>Evidence <strong>{{ $call->provider==='demo'?'Simulation':($call->isProviderVerified()?'Provider verified':'Unverified request') }}</strong></span></div>@if($call->error_message)<p class="help-note red-text">{{ $call->error_message }}</p>@endif @if(auth()->user()->isOwner() && $call->provider==='exotel')<form class="inline-form" method="post" action="{{ route('calls.reconcile',$call) }}">@csrf @unless($call->provider_sid)<input name="provider_sid" aria-label="Provider call reference" placeholder="Provider call SID" required>@endunless<button class="button subtle small">Verify with Exotel</button></form>@endif</div>@empty<div class="empty">No calls yet. The assigned employee can start one using the Call button.</div>@endforelse</div><div class="pagination-wrap">{{ $calls->links() }}</div></section>
<section class="panel"><div class="panel-heading"><h2>Lead timeline</h2><span class="muted">A complete trail</span></div><div class="timeline">@foreach($activities as $activity)<div class="timeline-item"><span class="timeline-dot"></span><div><div class="timeline-meta"><strong>{{ $activity->user?->name??'System' }}</strong><small>{{ \App\Support\India::display($activity->created_at,'d M, h:i A') }}</small></div><p>{{ $activity->description }}</p></div></div>@endforeach</div><div class="pagination-wrap">{{ $activities->links() }}</div></section></div>
<div class="stack"><section class="panel"><div class="panel-heading"><div><h2>Plan the next conversation</h2><p>Follow-up times are in IST</p></div></div><form class="panel-body stack" method="post" action="{{ route('follow-ups.store',$lead) }}">@csrf<label>Date and time<input type="datetime-local" name="due_at" value="{{ old('due_at') }}" required></label><label>What needs to happen?<textarea name="note" rows="3" maxlength="2000" placeholder="Call back with the proposal…" required></textarea></label><button class="button primary">Schedule follow-up</button></form></section><section class="panel"><div class="panel-heading"><h2>Follow-ups</h2></div><div class="panel-body stack">@forelse($followUps as $item)<div class="follow-card"><div class="follow-card-top"><strong>{{ \App\Support\India::display($item->due_at,'d M, h:i A') }}</strong><x-badge :value="$item->completed_at?'completed':($item->due_at->isPast()?'Overdue':'pending')"/></div><p>{{ $item->note }}</p><small class="muted">{{ $item->employee->name }}</small>@unless($item->completed_at)<form method="post" action="{{ route('follow-ups.update',$item) }}">@csrf @method('put')<input name="action" type="hidden" value="complete"><button class="button subtle small">Mark complete</button></form><details><summary>Reschedule</summary><form class="stack" action="{{ route('follow-ups.update',$item) }}" method="post">@csrf @method('put')<input type="hidden" name="action" value="reschedule"><label>New time · IST<input name="due_at" type="datetime-local" required></label><button class="button small">Save time</button></form></details>@endunless</div>@empty<p class="muted">No follow-ups scheduled.</p>@endforelse</div></section></div></div>
@endsection

@if(session('native_dial'))
<script>
    if (window.ReactNativeWebView) {
        window.ReactNativeWebView.postMessage(JSON.stringify({
            type: 'CALL_REQUEST',
            payload: @json(session('native_dial'))
        }));
    }
</script>
@endif
